# Change these first
owner: fletchto99 # Your GitHub organization or username, where this repository lives
repo: status.fletchto99.com # The name of this repository

sites:
  - name: Home
    url: $HOME_SITE
    maxResponseTime: 5000
  - name: Blog
    url: $BLOG_SITE
    maxResponseTime: 5000
  - name: Cloud
    url: $CLOUD_SITE
    maxResponseTime: 5000
  - name: Images
    url: $IMAGE_SITE
    maxResponseTime: 5000
  - name: Media
    url: $MEDIA_SITE
    maxResponseTime: 5000
  - name: Request
    url: $REQUEST_SITE
    maxResponseTime: 5000
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fletchto99.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Flethto99 Status
  introTitle: "Beep boop"
  introMessage: "Fletchto99's status page powered by GitHub Actions"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
