# Change these first
owner: fletchto99 # Your GitHub organization or username, where this repository lives
repo: status.fletchto99.com # The name of this repository

sites:
  - name: Home
    url: https://home.fletchto99.com
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/home-logo.png
  - name: Blog
    url: $BLOG_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/fletch-logo.png
  - name: Cloud
    url: $CLOUD_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/cloud-logo.png
  - name: Images
    url: $IMAGE_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/image-logo.png
  - name: Media
    url: $MEDIA_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/media-logo.png
  - name: Request
    url: $REQUEST_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/request-logo.png
  - name: Backups
    url: $BACKUPS_SITE
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/backups-logo.png
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.fletchto99.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/fletch-logo.png
  favicon: https://raw.githubusercontent.com/fletchto99/status.fletchto99.com/master/assets/fletch-logo.png
  name: "Flethto99's Status"
  navbar:
    - title: Status
      href: /
    - title: Incidents
      href: https://github.com/$OWNER/$REPO/issues

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
